name: frontend
description: A new Flutter project.
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen:
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  loading_animations: "^2.1.0"
  flutter_layout_grid: ^2.0.0
  carousel_slider: ^4.1.1
  firebase_auth: ^3.3.16
  cloud_firestore: ^3.1.13
  firebase_core : ^1.10.2
  provider: ^6.0.2
  shared_preferences: ^2.0.13
  fluttertoast: ^8.0.9
  email_validator: '^2.0.1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/svg/figures_dark_theme/
    - assets/svg/figures_light_theme/
    - assets/svg/icons/
    - assets/svg/loading/
    - assets/svg/spinners/
    - assets/images/

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend-Regular.ttf
          style: normal
        - asset: assets/fonts/Lexend-Bold.ttf
          weight: 700
          style: normal
    - family: Arantxa
      fonts:
        - asset: assets/fonts/Arantxa-Regular.ttf
          style: normal
        - asset: assets/fonts/Arantxa-Bold.ttf
          weight: 700
          style: normal

