name: Deploy to Firebase Hosting
on:
  push:
    tags:
      - hosting-v*
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - name: Build Web App
        run: |
            flutter build web
      - name: Host
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_CROW_2C36B }}'
          projectId: crow-2c36b
          channelId: live
